import Attribute from '../models/Attribute';

const attributesData = [
  {
    name: 'Finish Category',
    slug: 'finish-category',
    type: 'select' as const,
    isRequired: true,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 1,
    values: [
      { value: 'colorbond', label: 'Colorbond', sortOrder: 1 },
      { value: 'galvanised', label: 'Galvanised', sortOrder: 2 },
      { value: 'matt_colorbond', label: 'Matt Colorbond', sortOrder: 3 },
      { value: 'ultra', label: 'Ultra', sortOrder: 4 },
      { value: 'zinc', label: 'Zinc', sortOrder: 5 },
    ],
  },
  {
    name: 'Colour',
    slug: 'colour',
    type: 'color-swatch' as const,
    isRequired: true,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 2,
    values: [
      // === Colorbond (22 standard colours) ===
      { value: 'dover-white', label: 'Dover White', sortOrder: 1, metadata: { hex: '#E8E4D8', finishCategories: ['colorbond'] } },
      { value: 'surfmist', label: 'Surfmist', sortOrder: 2, metadata: { hex: '#D5D1C4', finishCategories: ['colorbond', 'matt_colorbond'] } },
      { value: 'southerly', label: 'Southerly', sortOrder: 3, metadata: { hex: '#C5BFA8', finishCategories: ['colorbond'] } },
      { value: 'shale-grey', label: 'Shale Grey', sortOrder: 4, metadata: { hex: '#B2B1A4', finishCategories: ['colorbond', 'matt_colorbond'] } },
      { value: 'bluegum', label: 'Bluegum', sortOrder: 5, metadata: { hex: '#8A8D85', finishCategories: ['colorbond'] } },
      { value: 'windspray', label: 'Windspray', sortOrder: 6, metadata: { hex: '#A0A19A', finishCategories: ['colorbond'] } },
      { value: 'basalt', label: 'Basalt', sortOrder: 7, metadata: { hex: '#6E6E6B', finishCategories: ['colorbond', 'matt_colorbond'] } },
      { value: 'classic-cream', label: 'Classic Cream', sortOrder: 8, metadata: { hex: '#D9CB8E', finishCategories: ['colorbond'] } },
      { value: 'paperbark', label: 'Paperbark', sortOrder: 9, metadata: { hex: '#C0B590', finishCategories: ['colorbond', 'matt_colorbond'] } },
      { value: 'evening-haze', label: 'Evening Haze', sortOrder: 10, metadata: { hex: '#B5AB8A', finishCategories: ['colorbond'] } },
      { value: 'dune', label: 'Dune', sortOrder: 11, metadata: { hex: '#A09878', finishCategories: ['colorbond', 'matt_colorbond'] } },
      { value: 'gully', label: 'Gully', sortOrder: 12, metadata: { hex: '#87826C', finishCategories: ['colorbond'] } },
      { value: 'jasper', label: 'Jasper', sortOrder: 13, metadata: { hex: '#7A7258', finishCategories: ['colorbond'] } },
      { value: 'manor-red', label: 'Manor Red', sortOrder: 14, metadata: { hex: '#5E2028', finishCategories: ['colorbond'] } },
      { value: 'wallaby', label: 'Wallaby', sortOrder: 15, metadata: { hex: '#8B8680', finishCategories: ['colorbond'] } },
      { value: 'woodland-grey', label: 'Woodland Grey', sortOrder: 16, metadata: { hex: '#5C5D4E', finishCategories: ['colorbond', 'matt_colorbond'] } },
      { value: 'pale-eucalypt', label: 'Pale Eucalypt', sortOrder: 17, metadata: { hex: '#6B7B52', finishCategories: ['colorbond'] } },
      { value: 'cottage-green', label: 'Cottage Green', sortOrder: 18, metadata: { hex: '#2D5A3D', finishCategories: ['colorbond'] } },
      { value: 'ironstone', label: 'Ironstone', sortOrder: 19, metadata: { hex: '#565E6B', finishCategories: ['colorbond'] } },
      { value: 'deep-ocean', label: 'Deep Ocean', sortOrder: 20, metadata: { hex: '#2C3E50', finishCategories: ['colorbond'] } },
      { value: 'night-sky', label: 'Night Sky', sortOrder: 21, metadata: { hex: '#1A1A2E', finishCategories: ['colorbond'] } },
      { value: 'monument', label: 'Monument', sortOrder: 22, metadata: { hex: '#3B3F3F', finishCategories: ['colorbond', 'matt_colorbond'] } },

      // === Matt Colorbond (admin can add more) ===
      { value: 'matt-monument', label: 'Matt Monument', sortOrder: 23, metadata: { hex: '#3B3F3F', finishCategories: ['matt_colorbond'] } },
      { value: 'matt-basalt', label: 'Matt Basalt', sortOrder: 24, metadata: { hex: '#6E6E6B', finishCategories: ['matt_colorbond'] } },

      // === Ultra (admin can add more) ===
      { value: 'ultra-monument', label: 'Ultra Monument', sortOrder: 25, metadata: { hex: '#383838', finishCategories: ['ultra'] } },
      { value: 'ultra-basalt', label: 'Ultra Basalt', sortOrder: 26, metadata: { hex: '#6A6C68', finishCategories: ['ultra'] } },

      // === Galvanised & Zinc ===
      { value: 'galvanised-steel', label: 'Galvanised Steel', sortOrder: 27, metadata: { hex: '#A8AAAD', finishCategories: ['galvanised'] } },
      { value: 'natural-zinc', label: 'Natural Zinc', sortOrder: 28, metadata: { hex: '#9DA0A0', finishCategories: ['zinc'] } },
    ],
  },
  {
    name: 'Thickness',
    slug: 'thickness',
    type: 'select' as const,
    unit: 'mm',
    isRequired: true,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 3,
    values: [
      { value: '0.35', label: '0.35mm', sortOrder: 1 },
      { value: '0.42', label: '0.42mm', sortOrder: 2 },
      { value: '0.48', label: '0.48mm', sortOrder: 3 },
      { value: '0.55', label: '0.55mm', sortOrder: 4 },
      { value: '0.60', label: '0.60mm', sortOrder: 5 },
      { value: '0.75', label: '0.75mm', sortOrder: 6 },
    ],
  },
  {
    name: 'Length',
    slug: 'length',
    type: 'number' as const,
    unit: 'm',
    isRequired: false,
    isFilterable: false,
    isVisibleOnProduct: true,
    sortOrder: 4,
    values: [],
  },
  {
    name: 'Material',
    slug: 'material',
    type: 'select' as const,
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 5,
    values: [
      { value: 'steel', label: 'Steel', sortOrder: 1 },
      { value: 'aluminium', label: 'Aluminium', sortOrder: 2 },
      { value: 'stainless-steel', label: 'Stainless Steel', sortOrder: 3 },
      { value: 'polycarbonate', label: 'Polycarbonate', sortOrder: 4 },
      { value: 'pvc', label: 'PVC', sortOrder: 5 },
    ],
  },
  {
    name: 'Profile Type',
    slug: 'profile-type',
    type: 'select' as const,
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 6,
    values: [
      { value: 'corrugated', label: 'Corrugated', sortOrder: 1 },
      { value: '5-rib', label: '5-Rib', sortOrder: 2 },
      { value: 'cliplock', label: 'Cliplock', sortOrder: 3 },
      { value: 'standing-seam', label: 'Standing Seam', sortOrder: 4 },
      { value: 'interlocking', label: 'Interlocking', sortOrder: 5 },
      { value: 'nailstrip', label: 'Nailstrip', sortOrder: 6 },
    ],
  },
  {
    name: 'Girth',
    slug: 'girth',
    type: 'select' as const,
    unit: 'mm',
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 7,
    values: [
      { value: '100', label: '100mm', sortOrder: 1 },
      { value: '150', label: '150mm', sortOrder: 2 },
      { value: '200', label: '200mm', sortOrder: 3 },
      { value: '250', label: '250mm', sortOrder: 4 },
      { value: '300', label: '300mm', sortOrder: 5 },
      { value: '350', label: '350mm', sortOrder: 6 },
      { value: '400', label: '400mm', sortOrder: 7 },
      { value: '450', label: '450mm', sortOrder: 8 },
      { value: '500', label: '500mm', sortOrder: 9 },
      { value: '600', label: '600mm', sortOrder: 10 },
      { value: '700', label: '700mm', sortOrder: 11 },
      { value: '800', label: '800mm', sortOrder: 12 },
      { value: '900', label: '900mm', sortOrder: 13 },
      { value: '1000', label: '1000mm', sortOrder: 14 },
    ],
  },
  {
    name: 'Folds',
    slug: 'folds',
    type: 'select' as const,
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 8,
    values: [
      { value: '2', label: '2 Folds', sortOrder: 1 },
      { value: '3', label: '3 Folds', sortOrder: 2 },
      { value: '4', label: '4 Folds', sortOrder: 3 },
      { value: '5', label: '5 Folds', sortOrder: 4 },
      { value: '6', label: '6 Folds', sortOrder: 5 },
      { value: '7', label: '7 Folds', sortOrder: 6 },
      { value: '8', label: '8 Folds', sortOrder: 7 },
    ],
  },
  {
    name: 'Sump Type',
    slug: 'sump-type',
    type: 'select' as const,
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 9,
    values: [
      { value: 'sump', label: 'Sump', sortOrder: 1 },
      { value: 'step-sump', label: 'Step Sump', sortOrder: 2 },
      { value: '1-high-sided', label: 'One High Sided Sump', sortOrder: 3 },
      { value: '2-high-sided', label: 'Two High Sided Sump', sortOrder: 4 },
    ],
  },
  {
    name: 'Sump Length',
    slug: 'sump-length',
    type: 'select' as const,
    unit: 'mm',
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 10,
    values: [
      { value: '600', label: '600mm', sortOrder: 1 },
      { value: '900', label: '900mm', sortOrder: 2 },
      { value: '1000', label: '1000mm', sortOrder: 3 },
    ],
  },
  {
    name: 'Sump Width',
    slug: 'sump-width',
    type: 'select' as const,
    unit: 'mm',
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 11,
    values: [
      { value: '600', label: '600mm', sortOrder: 1 },
      { value: '900', label: '900mm', sortOrder: 2 },
      { value: '1000', label: '1000mm', sortOrder: 3 },
    ],
  },
  {
    name: 'Sump Depth',
    slug: 'sump-depth',
    type: 'select' as const,
    unit: 'mm',
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 12,
    values: [
      { value: '100', label: '100mm', sortOrder: 1 },
      { value: '200', label: '200mm', sortOrder: 2 },
      { value: '300', label: '300mm', sortOrder: 3 },
      { value: '400', label: '400mm', sortOrder: 4 },
      { value: '500', label: '500mm', sortOrder: 5 },
      { value: '600', label: '600mm', sortOrder: 6 },
      { value: '700', label: '700mm', sortOrder: 7 },
      { value: '800', label: '800mm', sortOrder: 8 },
      { value: '900', label: '900mm', sortOrder: 9 },
      { value: '1000', label: '1000mm', sortOrder: 10 },
      { value: '1100', label: '1100mm', sortOrder: 11 },
      { value: '1200', label: '1200mm', sortOrder: 12 },
    ],
  },
  {
    name: 'Rib Size',
    slug: 'rib-size',
    type: 'select' as const,
    unit: 'mm',
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 13,
    values: [
      { value: '25', label: '25mm', sortOrder: 1 },
      { value: '38', label: '38mm', sortOrder: 2 },
    ],
  },
  {
    name: 'Cover Width',
    slug: 'cover-width',
    type: 'select' as const,
    unit: 'mm',
    isRequired: false,
    isFilterable: true,
    isVisibleOnProduct: true,
    sortOrder: 14,
    values: [
      { value: '210', label: '210mm', sortOrder: 1, metadata: { ribSizes: ['38'] } },
      { value: '230', label: '230mm', sortOrder: 2, metadata: { ribSizes: ['25'] } },
      { value: '310', label: '310mm', sortOrder: 3, metadata: { ribSizes: ['38'] } },
      { value: '330', label: '330mm', sortOrder: 4, metadata: { ribSizes: ['25'] } },
      { value: '510', label: '510mm', sortOrder: 5, metadata: { ribSizes: ['38'] } },
      { value: '530', label: '530mm', sortOrder: 6, metadata: { ribSizes: ['25'] } },
    ],
  },
];

export const seedAttributes = async () => {
  for (const attrData of attributesData) {
    await Attribute.findOneAndUpdate(
      { slug: attrData.slug },
      attrData,
      { upsert: true, new: true }
    );
  }
  console.log(`Seeded ${attributesData.length} attributes`);
};
